repositories:
  - name: elkouhen
    url: https://elkouhen-softwarefactory.github.io/app-charts/

releases:

  - name: books-api-dev2
    namespace: dev2
    chart: elkouhen/books-api
    values:
      - "./values.yaml"
