repositories:
  - name: elkouhen-charts
    url: https://elkouhen.github.io/charts

releases:

  - name: books-api-prod
    namespace: prod
    chart: elkouhen-charts/books-api
    values:
      - "./values.yaml"
      - image:
          repository: elkouhen-charts/books-api
          tag: {{ requiredEnv "IMAGE" }}