repositories:
  - name: elkouhen-charts
    url: https://elkouhen-softwarefactory.github.io/app-charts

releases:

  - name: books-api-dev3
    namespace: dev3
    chart: elkouhen-charts/books-api
    secrets:
      - "./secrets.yaml"
    values:
      - "./values.yaml"
      - image:
          repository: elkouhen/books-api
          tag: {{ requiredEnv "IMAGE" }}

        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            certmanager.k8s.io/issuer: letsencrypt-issuer
            kubernetes.io/tls-acme: "true"
            nginx.ingress.kubernetes.io/auth-secret: books-api-dev3-basicauthsecret
            nginx.ingress.kubernetes.io/auth-type: basic
          hosts:
            - books-api-dev3.melkouhen.net
          secretName: books-api-dev3-secret
          tls:
            - hosts:
                - books-api-dev3.melkouhen.net
              secretName: books-api-dev3-secret

        h2:
          enabled: false