repositories:
  - name: elkouhen
    url: https://elkouhen.github.io/charts/

releases:

  - name: books-api-dev
    namespace: dev
    chart: elkouhen/books-api
    values:
      - "./values.yaml"
      - image:
          repository: elkouhen/books-api
          tag: {{ requiredEnv "IMAGE" }}
        namespace: dev
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            certmanager.k8s.io/issuer: letsencrypt-issuer
            kubernetes.io/tls-acme: "true"
          hosts:
            - books-api-dev.melkouhen.net
              secretName: books-api-secret
          tls:
            - hosts:
              - books-api-dev.melkouhen.net
              secretName: books-api-secret
        service:
          type: LoadBalancer