repositories:
  - name: elkouhen
    url: https://elkouhen.github.io/charts/

releases:

  - name: books-api-dev
    namespace: dev
    chart: elkouhen/books-api
    values:
      - "./values.yaml"
      - image:
          repository: elkouhen/books-api
          tag: {{ requiredEnv "IMAGE" }}
        namespace: dev
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
          hosts:
            - books-api-dev.melkouhen.net
        service:
          type: LoadBalancer