repositories:
  - name: softeamouest-softwarefactory
    url: https://softeamouest-opus.github.io/charts

releases:

  - name: books-api-dev
    namespace: dev
    chart: elkouhen/books-api
    values:
      - "./values.yaml"
      - image:
          tag: {{ requiredEnv "IMAGE" }}
        namespace: dev
        ingress:
          enabled: false