auth:
  htpassword: YWRtaW46JGFwcjEkRHBnby5aaDYkTXpRTHBvQkVBSW0yamlwNzlvby56MQ==

ingress:
  annotations:
    nginx.ingress.kubernetes.io/auth-secret: books-api-prod-basicauthsecret
  secretName: books-api-prod-secret
  hosts:
  - books-api.k8.wildwidewest.xyz
  tls:
  - hosts:
    - books-api.k8.wildwidewest.xyz
    secretName: books-api-prod-secret

h2:
  enabled: true