auth:
  htpassword: YWRtaW46JGFwcjEkRHBnby5aaDYkTXpRTHBvQkVBSW0yamlwNzlvby56MQ==

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/auth-secret: books-api-dev-basicauthsecret
  hosts:
    - books-api-dev.melkouhen.net
  secretName: books-api-dev-secret
  tls:
    - hosts:
        - books-api-dev.melkouhen.net
      secretName: books-api-dev-secret

h2:
  enabled: false